### ISSUE TITLE
Docs: Add explanation for "IntOrString"

### ISSUE THREAD

**Issue by FlorianLudwig** [cdk8s-team/cdk8s#192]
### Description of the feature or enhancement:

From the document `getting-started/python.md`:

`k8s.ServicePort(port=80, target_port=k8s.IntOrString.from_number(8080))`

The documentation is missing an explanation what `k8s.IntOrString.from_number` is doing or why it is needed.

### Proposed Solution:

Either of:

1. Update documentation and add explanation
1. Remove `IntOrString` and allow using int or string instead of `imports.k8s.IntOrString` objects

---

This is a :rocket: Feature Request

**Comment by DeathRabbit679** [comment]
One thing I noticed when I did a reimport of some stuff with cdk8s version 1.0.0-beta.27 in typescript land, the `targetPort` for `ServicePort` which were previously not requiring `IntOrString.fromNumber()` now required me to put this everywhere. It uglied up the code a tad, but the real issue was a change deep in the generated code for importing `https://download.elastic.co/downloads/eck/1.5.0/all-in-one.yaml` a storage resource request to a `ElasticsearchSpecNodeSetsVolumeClaimTemplatesSpecResourcesRequests.fromString()` which neither my IDE or tsc caught, so when my elastic cluster failed to start, I only found this after hours of staring and comparing at the synth'd yaml. Indeed also using `IntOrString` works here as well, so I am curious to know what the exact situation is that requires `IntOrString`
