### ISSUE TITLE
Cannot create Namespace, construct is missing

### ISSUE THREAD

**Issue by jsnowacki** [cdk8s-team/cdk8s#618]
### Description of the bug:
Namespace creation is described [in the documentation](https://cdk8s.io/docs/latest/concepts/deps.html), but neither API Reference nor code completion is able to locate such a construct. Hence, there is no way to create namespace other than manual usage of `ApiObject` or adding manifest somehow differently, in my case via CDK. 

I'm posting is as a bug since it is mentioned in documentation thus it's IMO expected to be in `cdk8s`, but it's not.

### Reproduction Steps:
There should be some namespace construct in `cdk8s` or, better, `cdk8+`, e.g.:

```typescript
const namespace = new kplus.Namespace(chart, 'backend');
```

### Error Log:
No error as construct is missing.

### Environment:
  - **Framework Version**: v1.0.0-beta.10
  - **OS**: MacOSX and Linux

### Other:
NA

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
By default the namespace construct is now available as `KubeNamespace`. This is because the constructs generated by the `cdk8s import` command are now automatically prefixed with "Kube" to avoid naming conflicts. It's possible to disable this by running `cdk8s import k8s --no-class-prefix`.

Looks like the documentation may need updating - thanks for bringing this to our attention. 😄

**Comment by willin** [comment]
the origin config yaml:

```yaml
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: namespace1
  labels:
    name: namespace1
```

how to create the namespace?

doc ref: https://cdk8s.io/docs/latest/concepts/deps/#charts

where can i import `NamespaceChart` ?

**Comment by Chriscbr** [comment]
I believe that is an error as well - it should say `Chart` and not `NamespaceChart` or `ApplicationChart`.
