### ISSUE TITLE
make cdk8s and cdk v2 compatible (python)

### ISSUE THREAD

**Issue by trondhindenes** [cdk8s-team/cdk8s#772]
### Description of the feature or enhancement:
With the release of cdk 2.0, cdk8s and cdk are no longer compatible, since they require different versions of the "constructs" library. This is a problem for us, since we generally create one cdk app and one cdk8s app per service and have so far managed them in a single virtual environment

### Use Case:
to manage a single virtualenv for our deployments which consist of both cdk and cdk8s staks

### Proposed Solution:
N/A

### Other:
N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Chriscbr** [comment]
Thanks for creating this issue @trondhindenes! I noticed we actually already have an issue about this so I am going to close this one. (The issue was in the "cdk8s-core" repo, but I've just moved it now to "cdk8s" since I think it's more generally relevant here). 

See https://github.com/cdk8s-team/cdk8s/issues/773
