### ISSUE TITLE
Add documentation for creating construct libraries

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#794]
We should add a page to the website with information about how to author cdk8s construct libraries. Some of the content may overlap with the instructions for creating construct libraries for the AWS CDK, as described in the FAQ of Construct Hub: https://constructs.dev/contribute

**Comment by felipesere** [comment]
I'd be keen to work on this as we are looking to distribute a few pre-baked charts.
At the moment, when I install our package locally into a test project I get failures due to a parent chart not being found.

For some reason, `Chart.of(...)` fails for 
```
import { BasicApplication } from "shared/charts" // this is locally npm-installed

class X extends Chart {
   constructor(scope: Construct, id: string) {
     super(scope, id)
    
     new BasicApplication(this, `${id}-basic`, {
        // ... props elided....
     })
  }
}
```

Should I open a seprate bug for 🔼 or is that something better docs might address?

**Comment by Chriscbr** [comment]
@felipesere Yes please open a separate bug for this! Thank you :)

**Comment by felipesere** [comment]
I see you already have the PRs sorted 🌶️ .
Do you still need the issues?

**Comment by Chriscbr** [comment]
Nope, all good 👍
