### ISSUE TITLE
Cannot synth go web-service example

### ISSUE THREAD

**Issue by rogeliodh** [cdk8s-team/cdk8s#960]
### Description of the bug:
When trying to synthesize the go web-service example it fails

### Reproduction Steps:

```
# cdk8s import --language go 
Importing k8s v1.17.0...
Importing resources, this may take a few moments...
k8s
# cdk8s synth               
# example.com/web-service-go
./webservice.go:10:13: undefined: constructs.ConstructOptions
./webservice.go:18:24: undefined: constructs.ConstructOptions
Error: command "go run . " at /home/rogelio/dev/3rdparty/cdk8s/examples/go/web-service returned a non-zero exit code 2
    at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/cdk8s/2.0.80/libexec/lib/node_modules/cdk8s-cli/lib/util.js:50:27)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

### Error Log:
```
Error: command "go run . " at /home/rogelio/dev/3rdparty/cdk8s/examples/go/web-service returned a non-zero exit code 2
    at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/cdk8s/2.0.80/libexec/lib/node_modules/cdk8s-cli/lib/util.js:50:27)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

This is :bug: Bug Report

**Comment by vfarcic** [comment]
👍

**Comment by sumupitchayan** [comment]
Hi @rogeliodh. I was able to replicate this issue by creating a new cdk8s go app and then copying the code exactly as it is in the [webservice.go example](https://github.com/cdk8s-team/cdk8s-examples/tree/main/go/cdk8s-composition).

The problem seems to be the [first import in the webservice.go file](https://github.com/cdk8s-team/cdk8s-examples/blob/main/go/cdk8s-composition/webservice.go#L4):

```go
import (
	"example.com/cdk8s-composition/imports/k8s"
        ...
)
```

The path before `/imports/k8s` should be the same as the [module name in the first line of the `go.mod` file](https://github.com/cdk8s-team/cdk8s-examples/blob/main/go/cdk8s-composition/go.mod#L1):

```go
module example.com/cdk8s-composition
```

This module name will be different depending on the name of the directory you created the cdk8s app in. For example, if I create the cdk8s app in a folder called `go-demo`, my module name in the `go.mod` file will be `example.com/go-demo`. So, to use this in the `webservice.go` file I have to change the first import string to `example.com/go-demo/imports/k8s`. This should fix your issue.
